version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
before_build:
- cmd: msbuild /t:Restore
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: msbuild /t:Pack
artifacts:
- path: packages\*.nupkg
