name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Restore
      run: msbuild Mono.TextTemplating.sln -t:Restore -p:Configuration=Release -m
      
    - name: Build
      run: msbuild Mono.TextTemplating.sln -p:Configuration=Release -m
      
    - name: Download NUnit
      run: nuget install NUnit.ConsoleRunner -Version 3.8.0 -OutputDirectory testrunner
      
    - name: Test
      run: mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Mono.TextTemplating.Tests/bin/Release/net472/Mono.TextTemplating.Tests.dll
    
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: Packages
        path: packages\Release
